# Generated by Django 6.0.5 on 2026-06-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='authors/')),
                ('category', models.CharField(choices=[('poet', 'Поэт'), ('musician', 'Музыкант'), ('band', 'Группа'), ('writer', 'Писатель')], default='poet', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Дата рождения или основания группы', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Дата смерти или распада группы', null=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='genres/')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('work_type', models.CharField(choices=[('poem', 'Стихотворение'), ('song', 'Песня')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='works/')),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Продолжительность в секундах', null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='catalog.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='works', to='catalog.genre')),
            ],
        ),
    ]
