# Generated by Django 6.0.5 on 2026-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Год публикации или создания произведения', null=True),
        ),
    ]
