# Generated by Django 6.0.5 on 2026-07-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_work_publication_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='publication_date',
        ),
    ]
